# Generated by Django 3.2.12 on 2023-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='specs',
            field=models.ManyToManyField(related_name='monitors', to='sales.Spec'),
        ),
    ]
