# Generated by Django 3.2.12 on 2023-05-30 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_monitor_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Cores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hertz', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='power',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('serial', models.CharField(max_length=32)),
                ('power', models.FloatField()),
                ('cache', models.FloatField()),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.architecture')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.category')),
                ('cores', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.cores')),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.frequency')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.platform')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.socket')),
            ],
        ),
    ]
