# Generated by Django 3.2.12 on 2023-05-30 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20230530_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='specs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpus', to='sales.spec'),
            preserve_default=False,
        ),
    ]
