# Generated by Django 3.2.12 on 2023-05-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20230530_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='platform',
        ),
        migrations.AddField(
            model_name='cpu',
            name='platform',
            field=models.ManyToManyField(related_name='cpus', to='sales.Platform'),
        ),
    ]
