# Generated by Django 3.2.12 on 2023-05-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20230530_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='specs',
        ),
        migrations.AddField(
            model_name='cpu',
            name='specs',
            field=models.ManyToManyField(related_name='cpus', to='sales.Spec'),
        ),
    ]
