# Generated by Django 3.2.12 on 2023-05-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_app', '0002_auto_20230526_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='problem',
        ),
        migrations.CreateModel(
            name='Sym_to_Prob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='possible_causes', to='virtual_app.problem')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='caused_problems', to='virtual_app.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Prob_to_Sym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shown_symptoms', to='virtual_app.problem')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_conditions', to='virtual_app.symptom')),
            ],
        ),
        migrations.CreateModel(
            name='Prob_to_Sol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.FloatField()),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='solutions', to='virtual_app.problem')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='problems', to='virtual_app.solution')),
            ],
        ),
    ]
