# Generated by Django 3.2.12 on 2023-05-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_app', '0004_alter_sym_to_prob_symptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sym_to_prob',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_symtoms', to='virtual_app.problem'),
        ),
    ]
